name: AdvancedMonsters
version: '${version}'
main: kro.dodoworld.advancedmonsters.AdvancedMonsters
api-version: 1.18
authors: [ _dodoman ]
description: This plugin will give monster an ability
commands:
  ability:
    description: Returns unlocked monster abilities
    usage: /<command>
