name: AdvancedMonsters
version: beta-0.4.2
main: kro.dodoworld.advancedmonsters.AdvancedMonsters
api-version: 1.18
authors: [ _dodoman ]
description: This plugin will give monster an ability
commands:
  ability:
    description: Returns unlocked monster abilities
    usage: /<command>

  admminiboss:
    description: Command to spawn miniboss manually
    usage: /<command> <miniboss_name>
    permission: advancedmonsters.miniboss.spawn

permissions:
  advancedmonsters.*:
    description: Gives access to all AdvancedMonsters commands.
    children:
      advancedmonsters.miniboss.spawn: true

  advancedmonsters.miniboss.spawn:
    description: Allows you spawn miniboss with /admminiboss command.
    default: op